### ISSUE TITLE
Unable to compile usbtv driver with Kernel version 4.1.10

### ISSUE THREAD

**Issue by dee101k** [simon3z/usbtv#8]
Hi @simon3z 
Currently i am working on following kernel in Beaglebone Black.
4.1.10-ti-r21
I am trying to insert my usbtv module in this kernel version.I am using driver from following link
https://github.com/simon3z/usbtv
So i am able to successfully compile my usbtv driver with my linux headers linux-headers-4.1.10-ti-r21
But when i am inserting my module using insmod. Then I am getting following errors on dmesg

```
[  208.683602] usbtv: Unknown symbol vb2_queue_init (err 0)
[  208.683744] usbtv: Unknown symbol video_ioctl2 (err 0)
[  208.683824] usbtv: Unknown symbol v4l2_device_put (err 0)
[  208.683885] usbtv: Unknown symbol vb2_queue_release (err 0)
[  208.684039] usbtv: Unknown symbol vb2_ioctl_streamoff (err 0)
[  208.684282] usbtv: Unknown symbol vb2_ioctl_querybuf (err 0)
[  208.684348] usbtv: Unknown symbol v4l2_fh_open (err 0)
[  208.684447] usbtv: Unknown symbol video_devdata (err 0)
[  208.684508] usbtv: Unknown symbol vb2_fop_release (err 0)
[  208.684610] usbtv: Unknown symbol vb2_ioctl_dqbuf (err 0)
[  208.684669] usbtv: Unknown symbol vb2_ioctl_create_bufs (err 0)
[  208.684729] usbtv: Unknown symbol vb2_ioctl_prepare_buf (err 0)
[  208.684845] usbtv: Unknown symbol vb2_buffer_done (err 0)
[  208.684905] usbtv: Unknown symbol vb2_plane_vaddr (err 0)
[  208.684978] usbtv: Unknown symbol video_unregister_device (err 0)
[  208.685059] usbtv: Unknown symbol vb2_ioctl_qbuf (err 0)
[  208.685118] usbtv: Unknown symbol vb2_fop_mmap (err 0)
[  208.685188] usbtv: Unknown symbol vb2_vmalloc_memops (err 0)
[  208.685246] usbtv: Unknown symbol v4l2_device_disconnect (err 0)
[  208.685305] usbtv: Unknown symbol vb2_fop_read (err 0)
[  208.685363] usbtv: Unknown symbol v4l2_device_register (err 0)
[  208.685449] usbtv: Unknown symbol __video_register_device (err 0)
[  208.685530] usbtv: Unknown symbol vb2_ioctl_streamon (err 0)
[  208.685589] usbtv: Unknown symbol vb2_fop_poll (err 0)
[  208.685649] usbtv: Unknown symbol v4l2_device_unregister (err 0)
[  208.685718] usbtv: Unknown symbol video_device_release_empty (err 0)
[  208.685794] usbtv: Unknown symbol vb2_ioctl_reqbufs (err 0)
```

So can you please suggest some solution for above problem

**Comment by simon3z** [comment]
@dee101k this module (audio support) was included in the official kernel since 3.18. So you should have it already in 4.1.10.

**Comment by dee101k** [comment]
@simon3z ohk.. 
Then what should i do to properly compile my module in this kernel properly without errors...
i have tried earlier without compiling usbtv-audio.c file as well...But it resulted into same above errors
Please guide me related to it..

**Comment by simon3z** [comment]
@dee101k are you using debian? In general the module should be already available with your kernel so you should just use `modprobe usbtv` and that's all. Use `lsmod | grep usbtv` to check if the module is loaded.

**Comment by dee101k** [comment]
@simon3z no i am not using debian.I am using ubuntu 14.04.
I am perfectly able to do `modprobe usbtv` .And my usbtv module is also loading up.But when i am plugging my device then no /dev/video0 is coming up.It means my usbtv driver is not recognizing my Tv tuner Device.
I am using USBTV007 based Tv tuner with Product and Vendor Id : `1f71:3301`
Please guide me as how to compile your module in my kernel version without errors.

**Comment by prisme60** [comment]
Perhaps you didn't have a udev rule needed for the creation of the device
node on the dev directory. (This udev rule should also execute the modprobe
automatically)

**Comment by simon3z** [comment]
> @simon3z no i am not using debian.I am using ubuntu 14.04.
> I am perfectly able to do modprobe usbtv .And my usbtv module is also loading up.But when i am plugging my device then no /dev/video0 is coming up.It means my usbtv driver is not recognizing my Tv tuner Device.

@dee101k if the `usbtv` module is not recognizing your usb tv tuner (`1f71:3301`) then this module here won't help you.

In fact the supported devices are `1b71:3002`:

```
$ modinfo usbtv | grep alias
alias:          usb:v1B71p3002d*dc*dsc*dp*ic*isc*ip*in*

$ lsusb | grep Fushicai
Bus 001 Device 003: ID 1b71:3002 Fushicai USBTV007 Video Grabber [EasyCAP]
```

All the code you find here was already included in the kernel mainline 2 years ago.

**Comment by dee101k** [comment]
@simon3z 
I have also tried your usbtv Kernel Module on Ubuntu installed on my PC.The kernel version is `3.13.0-83-generic`.
I have changed Vendor ID and Product ID in your codes with my TV Tuner Product and Vendor ID.
On this,it is properly compiling and also working properly with /dev/video1 coming up.

So till now i am not able to understand why this usbtv module is working only on selected kernel versions?
Please tell me some workaround related to my problem.

**Comment by simon3z** [comment]
> So till now i am not able to understand why this usbtv module is working only on selected kernel versions?
> Please tell me some workaround related to my problem.

If you're using a kernel >= 3.18 you should use the usbtv module that comes with that kernel (includes the same code I have here and it compiles properly).

**Comment by dee101k** [comment]
@simon3z Finally i am able to work with usbtv driver available in Kernel Main line.
Since my Vendor ID and Product ID is not matching with vid and pid of usbtv driver...So i have to change it by going into following directory

```
modprobe usbtv
nano /sys/bus/usb/drivers/usbtv/new_id
```

So actually i wanted to learn more inside about usbtv driver and how to make some changes in the driver so can you please suggest me some links or literature regarding this driver.
