### ISSUE TITLE
Request: Support multiple video devices

### ISSUE THREAD

**Issue by vkulpa** [simon3z/usbtv#9]
Is this possible to have param to the module (default is 1) saying how many video devices should be created? I've tried to modify `usbtv-core.c` and duplicated code that creates/initializes `usbtv` struct. It created 2 devices but the first "died" when the second started stream. Unfortunately, I'm not good in C and in v4l2 and don't know how to do it.

Let me know if it's possible maybe there's another easiest way to duplicate existing video device.

**Comment by simon3z** [comment]
> Is this possible to have param to the module (default is 1) saying how many video devices should be created? I've tried to modify usbtv-core.c and duplicated code that creates/initializes usbtv struct. It created 2 devices but the first "died" then the second started stream. Unfortunately, I'm not good in C and in v4l2 and don't know how to do it.
> 
> Let me know if it's possible maybe there's another easiest way to duplicate existing video device.

@vkulpa this module is maintained in the main kernel now, so this question should be done on the kernel ml or bugzilla (or video subsystem).

**Comment by vkulpa** [comment]
@simon3z ok, great, tnx, for letting me know. Moving the question there and closing this one.
